# Use a lightweight base image with Python installed
FROM python:3.9-slim

# Set working directory
WORKDIR /app

# Copy files into container
COPY . .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Command to start the application
CMD uvicorn main:app --reload --host 0.0.0.0 --port 8000
